import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/Header"
import Provider from '@/app/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className='flex flex-col h-screen '>
            <Header />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}